#!/usr/bin/env bash
start_page=$1
end_page=$2
filepath=$3
filepath_without_ext="${filepath%.*}"

out_filepath="${filepath_without_ext}_pages_${start_page}_${end_page}.pdf"
[[ -z $4 ]] || out_filepath=$4

pdfseparate -f ${start_page} -l ${end_page} "${filepath}" "__tmp_page%05d.pdf"
pdfunite __tmp_page* "${out_filepath}"
rm __tmp_page*
